//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teespring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campaign()
        {
            this.user_campaign = new HashSet<user_campaign>();
        }
    
        public int id_campaign { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<double> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_campaign> user_campaign { get; set; }
    }
}
